apiVersion: apps/v1
kind: Deployment
metadata:
  name: ql-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ql-frontend
  template:
    metadata:
      labels:
        app: ql-frontend
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
